class Solution {
    public:
        string reorderSpaces(string text) {
               // "a" - edge test case
                      if(text.length()<2) return text;

                             //count the number of spaces 
                                    int spaces = 0;
                                           for(int i=0;i<text.size();++i){
                                                      if(text[i]==' ') spaces++;
                                                             } 
                                                                    //cout<<"spaces : "<<spaces<<endl;

                                                                           //split the string using stringstream and store the words in a vector
                                                                                  vector<string> temp;
                                                                                         istringstream ss(text);
                                                                                                string word;
                                                                                                       while(ss>>word){
                                                                                                                  temp.push_back(word);
                                                                                                                         }
                                                                                                                             //    for(int i=0;i<temp.size();++i){
                                                                                                                                 //        cout<<temp[i]<<" ";
                                                                                                                                     //    }


                                                                                                                                            //"  hello" - edge test case
                                                                                                                                                   /*If there is only word in the vector then there would 
                                                                                                                                                          be divide by 0 exception , so directly append the spaces 
                                                                                                                                                                 to the single word and return it*/
                                                                                                                                                                        if(temp.size()==1){
                                                                                                                                                                                   string ans2=temp[0];
                                                                                                                                                                                              while(spaces){
                                                                                                                                                                                                             ans2+=' ';
                                                                                                                                                                                                                            spaces--;
                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                  return ans2;
                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                       //calculate the number of optimal spaces between each word
                                                                                                                                                                                                                                                                              int optimal = spaces/(temp.size()-1);
                                                                                                                                                                                                                                                                                     //cout<<"optimal : "<<optimal<<endl;
                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                              //count the number of lastSpaces to be appended
                                                                                                                                                                                                                                                                                                     int lastSpace = spaces%(temp.size()-1);
                                                                                                                                                                                                                                                                                                            //cout<<"lastSpace : "<<lastSpace<<endl;
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                         //copying the value of optimal spaces into a , so that on decrementing into a while loop the value is not lost
                                                                                                                                                                                                                                                                                                                                int a = optimal;

                                                                                                                                                                                                                                                                                                                                       //declare a empty string ans
                                                                                                                                                                                                                                                                                                                                              string ans = "";
                                                                                                                                                                                                                                                                                                                                                     //traverse the vector temp and concatenate the words and the optimal spaces accordingly
                                                                                                                                                                                                                                                                                                                                                            for(int i=0;i<temp.size();++i){
                                                                                                                                                                                                                                                                                                                                                                       ans+=temp[i];
                                                                                                                                                                                                                                                                                                                                                                                  if(i!=temp.size()-1){
                                                                                                                                                                                                                                                                                                                                                                                             while(a){
                                                                                                                                                                                                                                                                                                                                                                                                            ans+=' ';
                                                                                                                                                                                                                                                                                                                                                                                                                           a--;
                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                             a=optimal;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //append the lastSpaces if any
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  while(lastSpace){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ans+=' ';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        lastSpace--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //return the string ans
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 };
